import { Fingerprint } from 'lucide-react'
import StatusPill from '../../components/StatusPill'
import { formatProbability } from '../../utils/helpers'

export default function VocoderPage({ selected }) {
  const vocoder = selected.vocoder_fingerprint || {}

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div>
        <p className="text-xs font-bold uppercase tracking-widest text-rose-400 font-mono">Module 03</p>
        <h1 className="text-3xl font-black text-white mt-1">Vocoder Fingerprinting</h1>
        <p className="text-sm text-slate-400 mt-2">
          Scans for high-frequency spectral artifacts generated by neural vocoders (e.g., WaveNet, HiFi-GAN).
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="rounded-xl border border-slate-800 bg-[#0c1017] p-5">
          <p className="text-[10px] uppercase font-mono text-slate-500">Detected Architecture</p>
          <p className="text-xl font-bold font-mono text-rose-300 mt-2">{vocoder.detected_tool ?? 'None Flagged'}</p>
        </div>
        <div className="rounded-xl border border-slate-800 bg-[#0c1017] p-5">
          <p className="text-[10px] uppercase font-mono text-slate-500">Artifact Confidence</p>
          <p className="text-xl font-bold font-mono text-cyan-300 mt-2">{formatProbability(vocoder.confidence)}</p>
        </div>
      </div>

      <div className="rounded-2xl border border-slate-800 bg-[#0c1017] p-6 space-y-4">
        <h3 className="text-sm font-bold text-white flex items-center gap-2">
          <Fingerprint size={16} className="text-rose-400" /> Synthetic Signature Detection
        </h3>
        <p className="text-xs text-slate-300 leading-relaxed">
          Neural text-to-speech pipelines rely on vocoders to reconstruct waveforms from spectrograms. This often leaves distinct periodic patterns or phase inconsistencies in upper frequency bins.
        </p>
        <div className="border-t border-slate-800 pt-4 flex items-center justify-between text-xs font-mono">
          <span className="text-slate-400">Vocoder Flag Status:</span>
          <StatusPill status={selected.vocoder_flag ? 'ANOMALOUS' : 'NORMAL'} />
        </div>
      </div>
    </div>
  )
}